---@alias onoma.Picker "snacks" | "telescope"

---@class onoma.SnacksConfig
---@field title? string

---@class onoma.TelescopeConfig
---@field results_title? string
---@field prompt_title? string
---@field preview_title? string

---@class onoma.Config
---@field picker? onoma.Picker | (onoma.Picker)[]
---@field debug? boolean
---@field snacks? onoma.SnacksConfig
---@field telescope? onoma.TelescopeConfig
---@field symbol_kinds? {string: onoma.SymbolKind[]}|onoma.SymbolKind[]

---@type onoma.Config
return {
	picker = { 'snacks' },
	debug = false,
	snacks = {
		title = 'Symbols (Onoma)',
	},
	telescope = {
		results_title = 'Symbols (Onoma)',
		prompt_title = '',
		preview_title = '',
	},
	symbol_kinds = {
		go = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		rust = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		lua = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		typescript = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		typescriptjsx = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		javascript = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		javascriptjsx = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		clojure = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
		python = {
			'Unknown',
			'AbstractMethod',
			'Class',
			'Constant',
			'Enum',
			'EnumMember',
			'Function',
			'Getter',
			'Interface',
			'Macro',
			'Method',
			'MethodAlias',
			'Module',
			'Namespace',
			'Object',
			'Package',
			'Property',
			'Setter',
			'SingletonClass',
			'SingletonMethod',
			'StaticDataMember',
			'StaticField',
			'StaticMethod',
			'StaticProperty',
			'StaticVariable',
			'Struct',
			'Trait',
			'TraitMethod',
			'Type',
			'TypeAlias',
			'TypeClass',
			'TypeClassMethod',
			'TypeFamily',
		},
	},
}
